/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import http.server.MHttpServer;

public class App {

    public String getGreeting() {
      return "Hello World!";
    }

    public static void main(String[] args) {
        // Vertx vertx = Vertx.vertx();
        // vertx.deployVerticle(new JokeVerticle());

        new MHttpServer().startServer();
    }
}
