/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http.client.howto;

import io.vertx.core.Vertx;

public class App {

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(new JokeVerticle());
    }
}
